---
- name: Installing tomcat9
  become: yes
  hosts: all
  vars:
    java_package: openjdk-11-jdk
    tomcat_username: tomcat
    tomcat_version: 9.0.63
    tomcat_home: /opt/tomcat
    tomcat_shell: /bin/false
  tasks:  
    - name: Install Java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: "{{ tomcat_username }}"
        home: "{{ tomcat_home }}"
        shell: "{{ tomcat_shell }}"
        state: present
    - name: download tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz 
        dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
    - name: untar tomcat
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: "{{ tomcat_home }}"
    - name: create a symlink
      ansible.builtin.file:
        src: "{{ tomcat_home }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ tomcat_home }}/latest"
        state: link
    - name: Recursively change ownership of a directory
      ansible.builtin.file:
        path: "{{ tomcat_home }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_username }}"
        group: "{{ tomcat_username }}"
    - name: finding sh files
      ansible.builtin.find:
        path: "{{ tomcat_home }}/latest/bin"
        pattern: "*.sh"
      register: shfiles   
    - name: print shfiles
      debug:
        var: shfiles
    - set_fact:
        tomcat_executables: "{{ shfiles.files | map(attribute='path') | list }}" 
    - name: print tomcatexcecutables
      debug:
        var: tomcat_executables    
    - name: execute permissions to .sh files
      ansible.builtin.file:
        path: "{{ items }}"
        mode: 0751
      with_items: "{{ tomcat_executables }}"  
    - name: copy service file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
      notify: 
        - reload and enable tomcat 
    - name: ensure tomcat is running
      ansible.builtin.systemd:
        name: tomcat.service
        state: started
  handlers:
    - name: reload and enable tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: restarted
         
        